# Generated by Django 5.1.7 on 2025-03-27 14:24

import django.contrib.postgres.fields.ranges
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CohortApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_short', models.CharField(db_index=True, max_length=100, verbose_name='Cohort Short Name')),
                ('name_full', models.CharField(max_length=1000, verbose_name='Cohort Full Name')),
                ('name_others', models.TextField(null=True, verbose_name='Previous/other/additional names (e.g. sub-cohorts)')),
                ('url', models.CharField(max_length=100, verbose_name='Cohort URL')),
                ('description', models.TextField(null=True, verbose_name='Cohort additional information')),
            ],
        ),
        migrations.CreateModel(
            name='GeneApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Gene name')),
                ('external_id', models.CharField(db_index=True, max_length=100, null=True, verbose_name='External ID')),
            ],
        ),
        migrations.CreateModel(
            name='MetaboliteApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Metabolite name')),
                ('external_id', models.CharField(db_index=True, max_length=100, null=True, verbose_name='External ID')),
            ],
        ),
        migrations.CreateModel(
            name='MolecularTraitApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Molecular trait name')),
                ('external_id', models.CharField(db_index=True, max_length=100, null=True, verbose_name='External ID')),
                ('type', models.CharField(choices=[('gene', 'gene'), ('protein', 'protein'), ('metabolite', 'metabolite')], default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformMasterApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Platform name')),
                ('full_name', models.CharField(max_length=100, verbose_name='Platform full name')),
                ('technic', models.CharField(max_length=100, verbose_name='Platform technic')),
                ('type', models.CharField(max_length=100, verbose_name='Platform type')),
            ],
        ),
        migrations.CreateModel(
            name='ProteinApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Protein name')),
                ('external_id', models.CharField(db_index=True, max_length=100, null=True, verbose_name='External ID')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmid', models.IntegerField(verbose_name='PubMed ID (PMID)')),
                ('doi', models.CharField(max_length=100, verbose_name='digital object identifier (doi)')),
                ('journal', models.CharField(max_length=100, verbose_name='Journal Name')),
                ('firstauthor', models.CharField(max_length=50, verbose_name='First Author')),
                ('authors', models.TextField(verbose_name='Authors')),
                ('title', models.TextField(verbose_name='Title')),
                ('date_publication', models.DateField(verbose_name='Publication Date')),
            ],
            options={
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='SampleApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.IntegerField(null=True, verbose_name='Number of Individuals')),
                ('sample_cases', models.IntegerField(null=True, verbose_name='Number of Cases')),
                ('sample_controls', models.IntegerField(null=True, verbose_name='Number of Controls')),
                ('sample_percent_female', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percent of Participants Who are Female')),
                ('sample_age', models.FloatField(null=True, verbose_name='Sample Age')),
                ('sample_age_sd', models.FloatField(null=True, verbose_name='Mean standard deviation of Age')),
            ],
        ),
        migrations.CreateModel(
            name='Phenotype',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Phenotype ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Phenotype Name')),
                ('category', models.CharField(max_length=100, null=True, verbose_name='Phenotype Category')),
                ('source', models.CharField(max_length=100, null=True, verbose_name='Phenotype source')),
                ('child_phenotype', models.ManyToManyField(related_name='parent_phenotype', to='applications.phenotype', verbose_name='Children Phenotype')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Platform name')),
                ('version', models.CharField(max_length=50, verbose_name='Platform version')),
                ('platform_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_version', to='applications.platformmasterapplications', verbose_name='Platform')),
            ],
        ),
        migrations.CreateModel(
            name='SampleApplicationsLegacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.IntegerField(null=True, verbose_name='Number of Individuals')),
                ('sample_cases', models.IntegerField(null=True, verbose_name='Number of Cases')),
                ('sample_percent_female', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percent of Participants Who are Female')),
                ('sample_age', models.FloatField(null=True, verbose_name='Sample Age')),
                ('sample_age_sd', models.FloatField(null=True, verbose_name='Mean standard deviation of Age')),
                ('platform_counts', models.JSONField(null=True, verbose_name='Associations by platform')),
                ('phenotype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phenotype_sample', to='applications.phenotype', verbose_name='Phenotype')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_id', models.CharField(db_index=True, max_length=30, verbose_name='Omicspred ID')),
                ('r2', models.FloatField(verbose_name='R2')),
                ('hr', models.FloatField(verbose_name='Hazard Ratio')),
                ('hr_ci', django.contrib.postgres.fields.ranges.DecimalRangeField(null=True, verbose_name='Hazard Ratio Confidence Interval')),
                ('fdr', models.FloatField(verbose_name='FDR adjusted P-value')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohort_score', to='applications.cohortapplications', verbose_name='Cohort')),
                ('genes', models.ManyToManyField(related_name='genes_score', to='applications.geneapplications', verbose_name='Genes')),
                ('metabolites', models.ManyToManyField(related_name='metabolites_score', to='applications.metaboliteapplications', verbose_name='Metabolites')),
                ('molecular_traits', models.ManyToManyField(related_name='molecular_trait_score', to='applications.moleculartraitapplications', verbose_name='Molecular traits')),
                ('phenotype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phenotype_score', to='applications.phenotype', verbose_name='Phenotype')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_score', to='applications.platformapplications', verbose_name='Platform')),
                ('proteins', models.ManyToManyField(related_name='proteins_score', to='applications.proteinapplications', verbose_name='Proteins')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication_score', to='applications.publicationapplications', verbose_name='Publication')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_score', to='applications.sampleapplications', verbose_name='Sample information')),
            ],
        ),
    ]
