# Generated by Django 5.2.4 on 2025-07-15 13:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_short', models.CharField(db_index=True, max_length=100, verbose_name='Cohort Short Name')),
                ('name_full', models.CharField(max_length=1000, verbose_name='Cohort Full Name')),
                ('name_others', models.TextField(null=True, verbose_name='Previous/other/additional names (e.g. sub-cohorts)')),
                ('url', models.CharField(max_length=100, verbose_name='Cohort URL')),
                ('description', models.TextField(null=True, verbose_name='Cohort additional information')),
            ],
        ),
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Molecular trait name')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('external_id', models.CharField(db_index=True, max_length=100, null=True, verbose_name='External ID')),
                ('external_id_source', models.CharField(max_length=100, null=True, verbose_name='External ID source')),
                ('synonyms', models.JSONField(null=True, verbose_name='Synonyms')),
                ('xrefs', models.JSONField(null=True, verbose_name='External references')),
                ('parent_external_id', models.CharField(max_length=100, null=True, verbose_name='External ID(s) of parent pathway(s)')),
                ('top_level', models.BooleanField(default=False, verbose_name='Top level pathway')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PathwayOld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Molecular trait name')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('external_id', models.CharField(db_index=True, max_length=100, null=True, verbose_name='External ID')),
                ('external_id_source', models.CharField(max_length=100, null=True, verbose_name='External ID source')),
                ('synonyms', models.JSONField(null=True, verbose_name='Synonyms')),
                ('xrefs', models.JSONField(null=True, verbose_name='External references')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Platform name')),
                ('version', models.CharField(max_length=50, verbose_name='Platform version')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Platform name')),
                ('full_name', models.CharField(max_length=100, verbose_name='Platform full name')),
                ('technic', models.CharField(max_length=100, verbose_name='Platform technic')),
                ('type', models.CharField(max_length=100, verbose_name='Platform type')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False, verbose_name='Publication Number (OPP)')),
                ('id', models.CharField(db_index=True, max_length=20, verbose_name='Publication ID (OPP)')),
                ('pmid', models.IntegerField(null=True, verbose_name='PubMed ID (PMID)')),
                ('doi', models.CharField(max_length=100, null=True, verbose_name='digital object identifier (doi)')),
                ('journal', models.CharField(max_length=100, verbose_name='Journal Name')),
                ('firstauthor', models.CharField(max_length=50, verbose_name='First Author')),
                ('authors', models.TextField(verbose_name='Authors')),
                ('title', models.TextField(verbose_name='Title')),
                ('date_publication', models.DateField(verbose_name='Publication Date')),
                ('date_released', models.DateField(db_index=True, null=True, verbose_name='OmicsPred Release Date')),
                ('curation_status', models.CharField(choices=[('C', 'Curated'), ('ID', 'Curated - insufficient data'), ('IP', 'Curation in Progress'), ('AW', 'Awaiting Curation'), ('E', 'Embargoed')], default='AW', max_length=2, verbose_name='Curation Status')),
                ('curation_notes', models.TextField(default='', verbose_name='Curation Notes')),
            ],
            options={
                'get_latest_by': 'num',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False, verbose_name='OmicsPred Number')),
                ('id', models.CharField(db_index=True, max_length=30, verbose_name='OmicsPred ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='OmicsPred Name')),
                ('trait_reported', models.TextField(null=True, verbose_name='Reported Trait')),
                ('trait_reported_id', models.CharField(null=True, verbose_name='Reported Trait ID')),
                ('method_name', models.TextField(verbose_name='Score Development Method')),
                ('method_params', models.TextField(null=True, verbose_name='Score Development Details/Relevant Parameters')),
                ('variants_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Variants')),
                ('variants_interactions', models.IntegerField(default=0, verbose_name='Number of Interaction Terms')),
                ('variants_genomebuild', models.CharField(default='NR', max_length=10, verbose_name='Original Genome Build')),
                ('date_released', models.DateField(db_index=True, null=True, verbose_name='OmicsPred Release Date')),
                ('curation_notes', models.TextField(default='', verbose_name='Curation Notes')),
                ('ancestry', models.JSONField(null=True, verbose_name='Ancestry distribution')),
                ('comment', models.TextField(null=True, verbose_name='Additional comment')),
                ('license', models.TextField(default='Creative Commons Attribution 4.0 International (CC BY 4.0)', verbose_name='License/Terms of Use')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('taxonomy_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='NCBI Taxonomy ID')),
                ('name', models.CharField(max_length=100, verbose_name='Common name')),
                ('name_latin', models.CharField(max_length=100, verbose_name='Latin name')),
            ],
        ),
        migrations.CreateModel(
            name='SuperPathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Molecular trait name')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('external_id', models.CharField(db_index=True, max_length=100, null=True, verbose_name='External ID')),
                ('external_id_source', models.CharField(max_length=100, null=True, verbose_name='External ID source')),
                ('synonyms', models.JSONField(null=True, verbose_name='Synonyms')),
                ('xrefs', models.JSONField(null=True, verbose_name='External references')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EFO',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Ontology ID')),
                ('label', models.CharField(db_index=True, max_length=500, verbose_name='Ontology Label')),
                ('description', models.TextField(null=True, verbose_name='Tissue/Trait Description')),
                ('url', models.CharField(max_length=500, verbose_name='Ontology URL')),
                ('type', models.CharField(max_length=100, null=True, verbose_name='Entry type')),
                ('child_efos', models.ManyToManyField(related_name='parent_efos', to='omicspred.efo', verbose_name='Children Ontology Entry')),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False, verbose_name='Dataset Number (OPD)')),
                ('id', models.CharField(db_index=True, max_length=20, verbose_name='Dataset ID (OPD)')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Dataset name')),
                ('omics_count', models.IntegerField(verbose_name='Omics Entities count')),
                ('omics_type', models.CharField(max_length=50, verbose_name='Omics type')),
                ('scores_count', models.IntegerField(verbose_name='Associated Scores count')),
                ('files_ids', models.JSONField(default=dict, verbose_name='Files IDs on Box')),
                ('tissue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tissue_dataset', to='omicspred.efo', verbose_name='Tissue')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_dataset', to='omicspred.platform', verbose_name='Platform')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='omicspred.publication', verbose_name='Publication')),
            ],
            options={
                'get_latest_by': 'num',
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Molecular trait name')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('external_id', models.CharField(db_index=True, max_length=100, null=True, verbose_name='External ID')),
                ('external_id_source', models.CharField(max_length=100, null=True, verbose_name='External ID source')),
                ('synonyms', models.JSONField(null=True, verbose_name='Synonyms')),
                ('xrefs', models.JSONField(null=True, verbose_name='External references')),
                ('biotype', models.CharField(max_length=100, null=True, verbose_name='Gene biotype')),
                ('retired_gene_model', models.BooleanField(default=False, verbose_name='Retired Gene ID/model')),
                ('pathways', models.ManyToManyField(related_name='pathway_genes', to='omicspred.pathway', verbose_name='Pathway(s)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Metabolite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Molecular trait name')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('external_id', models.CharField(db_index=True, max_length=100, null=True, verbose_name='External ID')),
                ('external_id_source', models.CharField(max_length=100, null=True, verbose_name='External ID source')),
                ('synonyms', models.JSONField(null=True, verbose_name='Synonyms')),
                ('xrefs', models.JSONField(null=True, verbose_name='External references')),
                ('pathways', models.ManyToManyField(related_name='pathway_metabolites', to='omicspred.pathway', verbose_name='Pathway(s)')),
                ('pathway_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pathway_group_metabolite', to='omicspred.pathwayold', verbose_name='Associated Pathway Group')),
                ('pathway_subgroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pathway_subgroup_metabolite', to='omicspred.pathwayold', verbose_name='Associated Pathway Subgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_type', models.CharField(choices=[('T', 'Training'), ('IV', 'Independent Validation'), ('EV', 'External Validation'), ('E', 'Evaluation')], default='', max_length=25, verbose_name='Evaluation Type')),
                ('performance_additional', models.TextField(default='', verbose_name='Additional Information')),
                ('source_gwas_catalog', models.CharField(max_length=20, null=True, verbose_name='GWAS Catalog Study ID (GCST...)')),
                ('source_doi', models.CharField(max_length=100, null=True, verbose_name='Source DOI')),
                ('covariates', models.TextField(null=True, verbose_name='Covariates Included in the Performance')),
                ('cohort_label', models.CharField(default='', max_length=100, verbose_name='Cohort label')),
                ('curation_notes', models.TextField(default='', verbose_name='Curation Notes')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dataset_performance', to='omicspred.dataset', verbose_name='Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PC', "Pearson's correlation"), ('SC', "Spearman's rank correlation")], db_index=True, default='Metric Type', max_length=40)),
                ('name', models.CharField(max_length=100, verbose_name='Performance Metric Name')),
                ('name_short', models.CharField(max_length=20, null=True, verbose_name='Performance Metric Name (Short)')),
                ('source', models.CharField(max_length=100, null=True, verbose_name='Performance Metric Source')),
                ('estimate', models.FloatField(verbose_name='Estimate')),
                ('pvalue', models.FloatField(null=True, verbose_name='p-value')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metric', to='omicspred.performance', verbose_name='PGS Performance Metric (PPM)')),
            ],
        ),
        migrations.AddField(
            model_name='platform',
            name='platform_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_version', to='omicspred.platformmaster', verbose_name='Platform'),
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Molecular trait name')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('external_id', models.CharField(db_index=True, max_length=100, null=True, verbose_name='External ID')),
                ('external_id_source', models.CharField(max_length=100, null=True, verbose_name='External ID source')),
                ('synonyms', models.JSONField(null=True, verbose_name='Synonyms')),
                ('xrefs', models.JSONField(null=True, verbose_name='External references')),
                ('gene', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gene_protein', to='omicspred.gene', verbose_name='Associated Gene')),
                ('pathways', models.ManyToManyField(related_name='pathway_proteins', to='omicspred.pathway', verbose_name='Pathway(s)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_version', models.CharField(max_length=50, verbose_name='Platform version')),
                ('tissue_name', models.CharField(max_length=100, null=True, verbose_name='Tissue name')),
                ('sample_number', models.IntegerField(null=True, verbose_name='Number of Individuals')),
                ('sample_percent_male', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percent of Participants Who are Male')),
                ('sample_age', models.FloatField(null=True, verbose_name='Sample Age')),
                ('sample_age_sd', models.FloatField(null=True, verbose_name='Mean standard deviation of Age')),
                ('ancestry_broad', models.CharField(max_length=250, verbose_name='Broad Ancestry Category')),
                ('ancestry_free', models.TextField(null=True, verbose_name='Ancestry (e.g. French, Chinese)')),
                ('ancestry_country', models.TextField(null=True, verbose_name='Country of Recruitment')),
                ('ancestry_additional', models.TextField(null=True, verbose_name='Additional Ancestry Description')),
                ('source_gwas_catalog', models.CharField(max_length=20, null=True, verbose_name='GWAS Catalog Study ID (GCST...)')),
                ('source_pmid', models.IntegerField(null=True, verbose_name='Source PubMed ID (PMID)')),
                ('source_doi', models.CharField(max_length=100, null=True, verbose_name='Source DOI')),
                ('cohorts_additional', models.TextField(null=True, verbose_name='Additional Sample/Cohort Information')),
                ('curation_notes', models.TextField(default='', verbose_name='Curation Notes')),
                ('cohorts', models.ManyToManyField(related_name='cohorts_sample', to='omicspred.cohort', verbose_name='Cohort(s)')),
            ],
        ),
        migrations.AddField(
            model_name='performance',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_performance', to='omicspred.sample', verbose_name='Performance Sample'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='samples_training',
            field=models.ManyToManyField(related_name='samples_training_dataset', to='omicspred.sample', verbose_name='Training sample(s)'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='samples_validation',
            field=models.ManyToManyField(related_name='samples_validation_dataset', to='omicspred.sample', verbose_name='Validation sample(s)'),
        ),
        migrations.CreateModel(
            name='SourceAnnotations',
            fields=[
                ('score', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='source_annotation_score', serialize=False, to='omicspred.score', verbose_name='OmicsPred Score')),
                ('annotations', models.JSONField(default=dict, verbose_name='Annotations')),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dataset_score', to='omicspred.dataset', verbose_name='Dataset'),
        ),
        migrations.AddField(
            model_name='score',
            name='genes',
            field=models.ManyToManyField(related_name='gene_score', to='omicspred.gene', verbose_name='Gene(s)'),
        ),
        migrations.AddField(
            model_name='score',
            name='metabolites',
            field=models.ManyToManyField(related_name='metabolite_score', to='omicspred.metabolite', verbose_name='Metabolite(s)'),
        ),
        migrations.AddField(
            model_name='score',
            name='proteins',
            field=models.ManyToManyField(related_name='protein_score', to='omicspred.protein', verbose_name='Protein(s)'),
        ),
        migrations.AddField(
            model_name='performance',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_performance', to='omicspred.score', verbose_name='Score'),
        ),
        migrations.AddField(
            model_name='score',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='species_score', to='omicspred.species', verbose_name='Species'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='species_dataset', to='omicspred.species', verbose_name='Species'),
        ),
        migrations.AddField(
            model_name='pathway',
            name='superpathways',
            field=models.ManyToManyField(related_name='subpathway', to='omicspred.superpathway', verbose_name='SuperPathway(s)'),
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Molecular trait name')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('external_id', models.CharField(db_index=True, max_length=100, null=True, verbose_name='External ID')),
                ('external_id_source', models.CharField(max_length=100, null=True, verbose_name='External ID source')),
                ('synonyms', models.JSONField(null=True, verbose_name='Synonyms')),
                ('xrefs', models.JSONField(null=True, verbose_name='External references')),
                ('biotype', models.CharField(max_length=100, null=True, verbose_name='Gene biotype')),
                ('gene', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gene_transcript', to='omicspred.gene', verbose_name='Associated Gene')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='score',
            name='transcripts',
            field=models.ManyToManyField(related_name='transcript_score', to='omicspred.transcript', verbose_name='Transcript(s)'),
        ),
    ]
