# Generated by Django 5.1.8 on 2025-04-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_id', models.CharField(db_index=True, max_length=20, verbose_name='Publication ID (OPP)')),
                ('pmid', models.IntegerField(verbose_name='PubMed ID (PMID)')),
                ('platform_name', models.CharField(max_length=100, verbose_name='Platform name')),
                ('dataset_id', models.CharField(db_index=True, max_length=20, verbose_name='Dataset ID (OPD)')),
                ('dataset_name', models.CharField(max_length=150, null=True, verbose_name='Dataset name')),
                ('plot_data', models.JSONField(default=dict, verbose_name='Plot data')),
                ('score_data', models.JSONField(default=dict, verbose_name='Score data')),
            ],
        ),
    ]
