"""
Django settings for OmicsPred project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

if not os.getenv('GAE_APPLICATION', None):
    app_settings = os.path.join('./', 'app.yaml')
    if os.path.exists(app_settings):
        import yaml
        with open(app_settings) as secrets_file:
            secrets = yaml.load(secrets_file, Loader=yaml.FullLoader)
            for keyword in secrets['env_variables']:
                os.environ[keyword] = secrets['env_variables'][keyword]
    elif not os.environ['SECRET_KEY']:
        print("Error: missing secret key")
        exit(1)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
if os.environ['DEBUG'] == 'True':
    DEBUG = True

# For Continuous integration (CI)
IS_TEST = False
if os.environ['IS_TEST'] == 'True':
    IS_TEST = True

# Flag to indicate whether the installation is for the public server or not
PUBLIC_SITE = False
if os.environ['PUBLIC_SITE'] == 'True':
    PUBLIC_SITE = True

#ALLOWED_HOSTS = []
ALLOWED_HOSTS = os.environ['ALLOWED_HOSTS'].split(',')



# Flags
if os.getenv('GAE_APPLICATION', None):
    OP_ON_GAE = 1
else:
    OP_ON_GAE = 0

# OP_ON_LIVE_SITE = False
# if 'OP_LIVE_SITE' in os.environ:
#     OP_ON_LIVE_SITE = True if os.environ['OP_LIVE_SITE'] in ['True', True] else False

# OP_ON_CURATION_SITE = False
# if 'OP_CURATION_SITE' in os.environ:
#     OP_ON_CURATION_SITE = True if os.environ['OP_CURATION_SITE'] in ['True', True] else False


# Application definition

INSTALLED_APPS = [
    'omicspred.apps.OmicspredConfig',
    'applications.apps.ApplicationsConfig',
    'plot.apps.PlotConfig',
    'rest_api.apps.RestApiConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders' # <= Added for test
]

# Test skipped app installation
if PUBLIC_SITE == False:
    elastic_search = [
        'search_es.apps.SearchESConfig',
        'django_elasticsearch_dsl'
    ]
    INSTALLED_APPS.extend(elastic_search)

# Local app installation
if OP_ON_GAE == 0:
    local_apps = [
        'django_extensions',
        'imports.apps.ImportsConfig'
    ]
    INSTALLED_APPS.extend(local_apps)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # <= Added for test
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG == True:
    debug_apps = [
        'debug_toolbar' # Debug SQL queries
    ]
    INSTALLED_APPS.extend(debug_apps)
    debug_middlewares = [
        'debug_toolbar.middleware.DebugToolbarMiddleware', # Debug SQL queries
    ]
    MIDDLEWARE.extend(debug_middlewares)

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# [START db_setup]
DB_ENGINE = 'django.db.backends.postgresql'
if OP_ON_GAE == 1:
    # Running on production App Engine, so connect to Google Cloud SQL using
    # the unix socket at /cloudsql/<your-cloudsql-connection string>
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': os.environ['DATABASE_NAME'],
            'USER': os.environ['DATABASE_USER'],
            'PASSWORD': os.environ['DATABASE_PASSWORD'],
            'HOST': os.environ['DATABASE_HOST'],
            'PORT': os.environ['DATABASE_PORT']
        },
        'applications': {
            'ENGINE': DB_ENGINE,
            'NAME': os.environ['DATABASE_NAME_2'],
            'USER': os.environ['DATABASE_USER_2'],
            'PASSWORD': os.environ['DATABASE_PASSWORD_2'],
            'HOST': os.environ['DATABASE_HOST_2'],
            'PORT': os.environ['DATABASE_PORT_2']
        },
        'plot': {
            'ENGINE': DB_ENGINE,
            'NAME': os.environ['DATABASE_NAME_3'],
            'USER': os.environ['DATABASE_USER_3'],
            'PASSWORD': os.environ['DATABASE_PASSWORD_3'],
            'HOST': os.environ['DATABASE_HOST_3'],
            'PORT': os.environ['DATABASE_PORT_3']
        }
    }
else:
     DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': os.environ['DATABASE_NAME'],
            'USER': os.environ['DATABASE_USER'],
            'PASSWORD': os.environ['DATABASE_PASSWORD'],
            'HOST': 'localhost',
            'PORT': os.environ['DATABASE_PORT_LOCAL']
        },
        'applications': {
            'ENGINE': DB_ENGINE,
            'NAME': os.environ['DATABASE_NAME_2'],
            'USER': os.environ['DATABASE_USER_2'],
            'PASSWORD': os.environ['DATABASE_PASSWORD_2'],
            'HOST': 'localhost',
            'PORT': os.environ['DATABASE_PORT_LOCAL_2']
        },
        'plot': {
            'ENGINE': DB_ENGINE,
            'NAME': os.environ['DATABASE_NAME_3'],
            'USER': os.environ['DATABASE_USER_3'],
            'PASSWORD': os.environ['DATABASE_PASSWORD_3'],
            'HOST': 'localhost',
            'PORT': os.environ['DATABASE_PORT_LOCAL_3']
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


INTERNAL_IPS = [
    "127.0.0.1",
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, "static/")

STATICFILES_FINDERS = [
	'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder'
]


#---------------------#
#  REST API Settings  #
#---------------------#

#REST_SAFELIST_IPS = [
#    '127.0.0.1'
#]
REST_BLACKLIST_IPS = [
    #'127.0.0.1'
]

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_api.rest_permissions.BlacklistPermission', # see REST_BLACKLIST_IPS
        #'rest_api.rest_permissions.SafelistPermission', # see REST_SAFELIST_IPS
        #'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        # 'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_api.pagination.CustomPagination',
    'PAGE_SIZE': 250,
    'EXCEPTION_HANDLER': 'rest_api.views.custom_exception_handler',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES' : {
        'anon': '100/min',
        'user': '100/min'
    }
}

# Display the Django REST framework interface only in dev/debug mode.
# Otherwise it simply displays the data (in JSON format) in the web browser.
if DEBUG == True:
    REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES'].append('rest_framework.renderers.BrowsableAPIRenderer')


#--------------------------#
#  Elasticsearch Settings  #
#--------------------------#

# Elasticsearch configuration
ELASTICSEARCH_DSL = {
    'default': {
        'hosts': os.environ['ELASTICSEARCH_URL_ROOT'],
        'timeout': 180  # Custom timeout
    }
}

ELASTICSEARCH_INDEX_SETTINGS = {
    'number_of_shards': 1,
    'number_of_replicas': 0
}

# Name of the Elasticsearch index
ELASTICSEARCH_INDEX_NAMES = {
    'search_es.documents.gene': 'gene',
    'search_es.documents.metabolite': 'metabolite',
    'search_es.documents.pathway': 'pathway',
    'search_es.documents.phenotype': 'phenotype',
    'search_es.documents.protein': 'protein',
    'search_es.documents.score': 'score'
}


#-----------------#
#  CORS Settings  #
#-----------------#
CORS_URLS_REGEX = r'^/(api|es_search)/.*$'
if OP_ON_GAE == 1:
    if PUBLIC_SITE == False:
        CORS_ALLOWED_ORIGINS = [
            'https//www.omicspred.org'
        ]
        CORS_ALLOWED_ORIGIN_REGEXES = [
            r"^"+os.environ['CORS_REGEXP']
        ]
    else:
        CORS_URLS_REGEX = r'^/api/.*$'

CORS_ALLOW_METHODS = ['GET']
CORS_ALLOW_ALL_ORIGINS = True
